### ISSUE TITLE
Add GPU compatibility using RAPIDS

### ISSUE THREAD

**Issue by jacanchaplais** [jacanchaplais/graphicle#24]
CuPy, CuDF and CuGraph appear to offer all functionality needed to perform the same operations on GPU. Use strategy pattern or the like to offer CPU or GPU data structures, and create GPU alternative algorithms.

**Comment by beckernick** [comment]
Hi! I came across this issue due to the GPU framework mentions (I work on some of these projects). If they were missing any functionality you needed or didn't provide the right user experience for your codebase/development process, please let me know! Would love to learn more.

**Comment by jacanchaplais** [comment]
Hi Nick, that's kind of you! I did find that there were some compatibility issues with the dependencies for CuGraph, CuPy, and CuDF. May have been the version of cudatoolkit they were using. But at the moment GPU acceleration for this library is no longer a priority. Thanks for getting in touch!
