### ISSUE TITLE
Dependency on Python >3.8

### ISSUE THREAD

**Issue by Kieran-Mg1** [jacanchaplais/graphicle#41]
Minor issue, just thought I'd mention that currently, graphicle requires at Python version >3.8 to avoid the error `Module 'functools' has no attribute 'cached_property'`, which didn't exist before 3.8. Apologies if this dependancy is already mentioned somewhere and I missed it.

**Comment by jacanchaplais** [comment]
Thank you @Kieran-Mg1! Maybe it's mentioned somewhere, though the desired behaviour should be to have the build system refuse to install with earlier than 3.8, so I shall add a patch.

**Comment by jacanchaplais** [comment]
Turns out I didn't even use those functions in the current version, so simple enough to just remove and maintain further backward compatibility. Thanks for pointing this out, `graphicle==0.1.2` has been added to PyPI.
